SYSTEM Linux
ENVIRONMENT PRO
EOS_HOST http://mainnet.eoscalgary.io
DB_NAME pro-baccarat
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.7/logging/__init__.py", line 983, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 829, in format
    return fmt.format(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 569, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.7/logging/__init__.py", line 331, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib64/python3.7/threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.7/socketserver.py", line 647, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.7/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.7/socketserver.py", line 717, in __init__
    self.handle()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 293, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib64/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 328, in handle_one_request
    return self.run_wsgi()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ec2-user/opt/python/baccarat-server/app/views.py", line 73, in generate_seed
    m = SEED_SERVICE.get_seed(int(room_id), int(game_id))
  File "/home/ec2-user/opt/python/baccarat-server/app/service/seed_service.py", line 37, in get_seed
    logging.info("从DB返回seed数据为空 roomid=%d gameid", room_id, game_id)
Message: '从DB返回seed数据为空 roomid=%d gameid'
Arguments: (11, 384)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.7/logging/__init__.py", line 983, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 829, in format
    return fmt.format(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 569, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.7/logging/__init__.py", line 331, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib64/python3.7/threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.7/socketserver.py", line 647, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.7/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.7/socketserver.py", line 717, in __init__
    self.handle()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 293, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib64/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 328, in handle_one_request
    return self.run_wsgi()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ec2-user/opt/python/baccarat-server/app/views.py", line 73, in generate_seed
    m = SEED_SERVICE.get_seed(int(room_id), int(game_id))
  File "/home/ec2-user/opt/python/baccarat-server/app/service/seed_service.py", line 37, in get_seed
    logging.info("从DB返回seed数据为空 roomid=%d gameid", room_id, game_id)
Message: '从DB返回seed数据为空 roomid=%d gameid'
Arguments: (11, 384)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.7/logging/__init__.py", line 983, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 829, in format
    return fmt.format(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 569, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.7/logging/__init__.py", line 331, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib64/python3.7/threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.7/socketserver.py", line 647, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.7/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.7/socketserver.py", line 717, in __init__
    self.handle()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 293, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib64/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 328, in handle_one_request
    return self.run_wsgi()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ec2-user/opt/python/baccarat-server/app/views.py", line 73, in generate_seed
    m = SEED_SERVICE.get_seed(int(room_id), int(game_id))
  File "/home/ec2-user/opt/python/baccarat-server/app/service/seed_service.py", line 37, in get_seed
    logging.info("从DB返回seed数据为空 roomid=%d gameid", room_id, game_id)
Message: '从DB返回seed数据为空 roomid=%d gameid'
Arguments: (11, 384)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.7/logging/__init__.py", line 983, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 829, in format
    return fmt.format(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 569, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.7/logging/__init__.py", line 331, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib64/python3.7/threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.7/socketserver.py", line 647, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.7/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.7/socketserver.py", line 717, in __init__
    self.handle()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 293, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib64/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 328, in handle_one_request
    return self.run_wsgi()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ec2-user/opt/python/baccarat-server/app/views.py", line 73, in generate_seed
    m = SEED_SERVICE.get_seed(int(room_id), int(game_id))
  File "/home/ec2-user/opt/python/baccarat-server/app/service/seed_service.py", line 37, in get_seed
    logging.info("从DB返回seed数据为空 roomid=%d gameid", room_id, game_id)
Message: '从DB返回seed数据为空 roomid=%d gameid'
Arguments: (11, 384)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.7/logging/__init__.py", line 983, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 829, in format
    return fmt.format(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 569, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.7/logging/__init__.py", line 331, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib64/python3.7/threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.7/socketserver.py", line 647, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.7/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.7/socketserver.py", line 717, in __init__
    self.handle()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 293, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib64/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 328, in handle_one_request
    return self.run_wsgi()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ec2-user/opt/python/baccarat-server/app/views.py", line 73, in generate_seed
    m = SEED_SERVICE.get_seed(int(room_id), int(game_id))
  File "/home/ec2-user/opt/python/baccarat-server/app/service/seed_service.py", line 37, in get_seed
    logging.info("从DB返回seed数据为空 roomid=%d gameid", room_id, game_id)
Message: '从DB返回seed数据为空 roomid=%d gameid'
Arguments: (11, 384)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.7/logging/__init__.py", line 983, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 829, in format
    return fmt.format(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 569, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.7/logging/__init__.py", line 331, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib64/python3.7/threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.7/socketserver.py", line 647, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.7/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.7/socketserver.py", line 717, in __init__
    self.handle()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 293, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib64/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 328, in handle_one_request
    return self.run_wsgi()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ec2-user/opt/python/baccarat-server/app/views.py", line 73, in generate_seed
    m = SEED_SERVICE.get_seed(int(room_id), int(game_id))
  File "/home/ec2-user/opt/python/baccarat-server/app/service/seed_service.py", line 37, in get_seed
    logging.info("从DB返回seed数据为空 roomid=%d gameid", room_id, game_id)
Message: '从DB返回seed数据为空 roomid=%d gameid'
Arguments: (11, 384)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.7/logging/__init__.py", line 983, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 829, in format
    return fmt.format(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 569, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.7/logging/__init__.py", line 331, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib64/python3.7/threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.7/socketserver.py", line 647, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.7/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.7/socketserver.py", line 717, in __init__
    self.handle()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 293, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib64/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 328, in handle_one_request
    return self.run_wsgi()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ec2-user/opt/python/baccarat-server/app/views.py", line 73, in generate_seed
    m = SEED_SERVICE.get_seed(int(room_id), int(game_id))
  File "/home/ec2-user/opt/python/baccarat-server/app/service/seed_service.py", line 37, in get_seed
    logging.info("从DB返回seed数据为空 roomid=%d gameid", room_id, game_id)
Message: '从DB返回seed数据为空 roomid=%d gameid'
Arguments: (11, 384)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.7/logging/__init__.py", line 983, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 829, in format
    return fmt.format(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 569, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.7/logging/__init__.py", line 331, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib64/python3.7/threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.7/socketserver.py", line 647, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.7/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.7/socketserver.py", line 717, in __init__
    self.handle()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 293, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib64/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 328, in handle_one_request
    return self.run_wsgi()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ec2-user/opt/python/baccarat-server/app/views.py", line 73, in generate_seed
    m = SEED_SERVICE.get_seed(int(room_id), int(game_id))
  File "/home/ec2-user/opt/python/baccarat-server/app/service/seed_service.py", line 37, in get_seed
    logging.info("从DB返回seed数据为空 roomid=%d gameid", room_id, game_id)
Message: '从DB返回seed数据为空 roomid=%d gameid'
Arguments: (11, 384)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.7/logging/__init__.py", line 983, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 829, in format
    return fmt.format(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 569, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.7/logging/__init__.py", line 331, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib64/python3.7/threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.7/socketserver.py", line 647, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.7/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.7/socketserver.py", line 717, in __init__
    self.handle()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 293, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib64/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 328, in handle_one_request
    return self.run_wsgi()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ec2-user/opt/python/baccarat-server/app/views.py", line 73, in generate_seed
    m = SEED_SERVICE.get_seed(int(room_id), int(game_id))
  File "/home/ec2-user/opt/python/baccarat-server/app/service/seed_service.py", line 37, in get_seed
    logging.info("从DB返回seed数据为空 roomid=%d gameid", room_id, game_id)
Message: '从DB返回seed数据为空 roomid=%d gameid'
Arguments: (11, 384)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.7/logging/__init__.py", line 983, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 829, in format
    return fmt.format(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 569, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.7/logging/__init__.py", line 331, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib64/python3.7/threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.7/socketserver.py", line 647, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.7/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.7/socketserver.py", line 717, in __init__
    self.handle()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 293, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib64/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 328, in handle_one_request
    return self.run_wsgi()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ec2-user/opt/python/baccarat-server/app/views.py", line 73, in generate_seed
    m = SEED_SERVICE.get_seed(int(room_id), int(game_id))
  File "/home/ec2-user/opt/python/baccarat-server/app/service/seed_service.py", line 37, in get_seed
    logging.info("从DB返回seed数据为空 roomid=%d gameid", room_id, game_id)
Message: '从DB返回seed数据为空 roomid=%d gameid'
Arguments: (11, 384)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.7/logging/__init__.py", line 983, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 829, in format
    return fmt.format(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 569, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.7/logging/__init__.py", line 331, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib64/python3.7/threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.7/socketserver.py", line 647, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.7/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.7/socketserver.py", line 717, in __init__
    self.handle()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 293, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib64/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 328, in handle_one_request
    return self.run_wsgi()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ec2-user/opt/python/baccarat-server/app/views.py", line 73, in generate_seed
    m = SEED_SERVICE.get_seed(int(room_id), int(game_id))
  File "/home/ec2-user/opt/python/baccarat-server/app/service/seed_service.py", line 37, in get_seed
    logging.info("从DB返回seed数据为空 roomid=%d gameid", room_id, game_id)
Message: '从DB返回seed数据为空 roomid=%d gameid'
Arguments: (11, 384)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.7/logging/__init__.py", line 983, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 829, in format
    return fmt.format(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 569, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.7/logging/__init__.py", line 331, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib64/python3.7/threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.7/socketserver.py", line 647, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.7/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.7/socketserver.py", line 717, in __init__
    self.handle()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 293, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib64/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 328, in handle_one_request
    return self.run_wsgi()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ec2-user/opt/python/baccarat-server/app/views.py", line 73, in generate_seed
    m = SEED_SERVICE.get_seed(int(room_id), int(game_id))
  File "/home/ec2-user/opt/python/baccarat-server/app/service/seed_service.py", line 37, in get_seed
    logging.info("从DB返回seed数据为空 roomid=%d gameid", room_id, game_id)
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 20 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 20 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 20 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 20 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 20 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 20 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 20 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 20 times.
Still searching for a signature. Tried 30 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 20 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 10 times.
Still searching for a signature. Tried 20 times.
Still searching for a signature. Tried 10 times.Message: '从DB返回seed数据为空 roomid=%d gameid'
Arguments: (11, 384)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.7/logging/__init__.py", line 983, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 829, in format
    return fmt.format(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 569, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.7/logging/__init__.py", line 331, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib64/python3.7/threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.7/socketserver.py", line 647, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.7/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.7/socketserver.py", line 717, in __init__
    self.handle()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 293, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib64/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 328, in handle_one_request
    return self.run_wsgi()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ec2-user/opt/python/baccarat-server/app/views.py", line 73, in generate_seed
    m = SEED_SERVICE.get_seed(int(room_id), int(game_id))
  File "/home/ec2-user/opt/python/baccarat-server/app/service/seed_service.py", line 37, in get_seed
    logging.info("从DB返回seed数据为空 roomid=%d gameid", room_id, game_id)
Message: '从DB返回seed数据为空 roomid=%d gameid'
Arguments: (11, 384)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.7/logging/__init__.py", line 983, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 829, in format
    return fmt.format(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 569, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.7/logging/__init__.py", line 331, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib64/python3.7/threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.7/socketserver.py", line 647, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.7/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.7/socketserver.py", line 717, in __init__
    self.handle()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 293, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib64/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 328, in handle_one_request
    return self.run_wsgi()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ec2-user/opt/python/baccarat-server/app/views.py", line 73, in generate_seed
    m = SEED_SERVICE.get_seed(int(room_id), int(game_id))
  File "/home/ec2-user/opt/python/baccarat-server/app/service/seed_service.py", line 37, in get_seed
    logging.info("从DB返回seed数据为空 roomid=%d gameid", room_id, game_id)
Message: '从DB返回seed数据为空 roomid=%d gameid'
Arguments: (11, 392)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.7/logging/__init__.py", line 983, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 829, in format
    return fmt.format(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 569, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.7/logging/__init__.py", line 331, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib64/python3.7/threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.7/socketserver.py", line 647, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.7/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.7/socketserver.py", line 717, in __init__
    self.handle()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 293, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib64/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 328, in handle_one_request
    return self.run_wsgi()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ec2-user/opt/python/baccarat-server/app/views.py", line 73, in generate_seed
    m = SEED_SERVICE.get_seed(int(room_id), int(game_id))
  File "/home/ec2-user/opt/python/baccarat-server/app/service/seed_service.py", line 37, in get_seed
    logging.info("从DB返回seed数据为空 roomid=%d gameid", room_id, game_id)
Message: '从DB返回seed数据为空 roomid=%d gameid'
Arguments: (11, 392)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.7/logging/__init__.py", line 983, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 829, in format
    return fmt.format(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 569, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.7/logging/__init__.py", line 331, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib64/python3.7/threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.7/socketserver.py", line 647, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.7/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.7/socketserver.py", line 717, in __init__
    self.handle()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 293, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib64/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 328, in handle_one_request
    return self.run_wsgi()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ec2-user/opt/python/baccarat-server/app/views.py", line 73, in generate_seed
    m = SEED_SERVICE.get_seed(int(room_id), int(game_id))
  File "/home/ec2-user/opt/python/baccarat-server/app/service/seed_service.py", line 37, in get_seed
    logging.info("从DB返回seed数据为空 roomid=%d gameid", room_id, game_id)
Message: '从DB返回seed数据为空 roomid=%d gameid'
Arguments: (11, 392)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.7/logging/__init__.py", line 983, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 829, in format
    return fmt.format(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 569, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.7/logging/__init__.py", line 331, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib64/python3.7/threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.7/socketserver.py", line 647, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.7/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.7/socketserver.py", line 717, in __init__
    self.handle()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 293, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib64/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 328, in handle_one_request
    return self.run_wsgi()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ec2-user/opt/python/baccarat-server/app/views.py", line 73, in generate_seed
    m = SEED_SERVICE.get_seed(int(room_id), int(game_id))
  File "/home/ec2-user/opt/python/baccarat-server/app/service/seed_service.py", line 37, in get_seed
    logging.info("从DB返回seed数据为空 roomid=%d gameid", room_id, game_id)
Message: '从DB返回seed数据为空 roomid=%d gameid'
Arguments: (11, 392)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.7/logging/__init__.py", line 983, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 829, in format
    return fmt.format(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 569, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.7/logging/__init__.py", line 331, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib64/python3.7/threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.7/socketserver.py", line 647, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.7/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.7/socketserver.py", line 717, in __init__
    self.handle()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 293, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib64/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 328, in handle_one_request
    return self.run_wsgi()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ec2-user/opt/python/baccarat-server/app/views.py", line 73, in generate_seed
    m = SEED_SERVICE.get_seed(int(room_id), int(game_id))
  File "/home/ec2-user/opt/python/baccarat-server/app/service/seed_service.py", line 37, in get_seed
    logging.info("从DB返回seed数据为空 roomid=%d gameid", room_id, game_id)
Message: '从DB返回seed数据为空 roomid=%d gameid'
Arguments: (11, 392)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.7/logging/__init__.py", line 983, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 829, in format
    return fmt.format(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 569, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.7/logging/__init__.py", line 331, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib64/python3.7/threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.7/socketserver.py", line 647, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.7/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.7/socketserver.py", line 717, in __init__
    self.handle()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 293, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib64/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 328, in handle_one_request
    return self.run_wsgi()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ec2-user/opt/python/baccarat-server/app/views.py", line 73, in generate_seed
    m = SEED_SERVICE.get_seed(int(room_id), int(game_id))
  File "/home/ec2-user/opt/python/baccarat-server/app/service/seed_service.py", line 37, in get_seed
    logging.info("从DB返回seed数据为空 roomid=%d gameid", room_id, game_id)
Message: '从DB返回seed数据为空 roomid=%d gameid'
Arguments: (11, 392)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.7/logging/__init__.py", line 983, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 829, in format
    return fmt.format(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 569, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.7/logging/__init__.py", line 331, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib64/python3.7/threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.7/socketserver.py", line 647, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.7/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.7/socketserver.py", line 717, in __init__
    self.handle()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 293, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib64/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 328, in handle_one_request
    return self.run_wsgi()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ec2-user/opt/python/baccarat-server/app/views.py", line 73, in generate_seed
    m = SEED_SERVICE.get_seed(int(room_id), int(game_id))
  File "/home/ec2-user/opt/python/baccarat-server/app/service/seed_service.py", line 37, in get_seed
    logging.info("从DB返回seed数据为空 roomid=%d gameid", room_id, game_id)
Message: '从DB返回seed数据为空 roomid=%d gameid'
Arguments: (11, 392)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.7/logging/__init__.py", line 983, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 829, in format
    return fmt.format(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 569, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.7/logging/__init__.py", line 331, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib64/python3.7/threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.7/socketserver.py", line 647, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.7/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.7/socketserver.py", line 717, in __init__
    self.handle()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 293, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib64/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 328, in handle_one_request
    return self.run_wsgi()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ec2-user/opt/python/baccarat-server/app/views.py", line 73, in generate_seed
    m = SEED_SERVICE.get_seed(int(room_id), int(game_id))
  File "/home/ec2-user/opt/python/baccarat-server/app/service/seed_service.py", line 37, in get_seed
    logging.info("从DB返回seed数据为空 roomid=%d gameid", room_id, game_id)
Message: '从DB返回seed数据为空 roomid=%d gameid'
Arguments: (11, 392)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.7/logging/__init__.py", line 983, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 829, in format
    return fmt.format(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 569, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.7/logging/__init__.py", line 331, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib64/python3.7/threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.7/socketserver.py", line 647, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.7/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.7/socketserver.py", line 717, in __init__
    self.handle()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 293, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib64/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 328, in handle_one_request
    return self.run_wsgi()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ec2-user/opt/python/baccarat-server/app/views.py", line 73, in generate_seed
    m = SEED_SERVICE.get_seed(int(room_id), int(game_id))
  File "/home/ec2-user/opt/python/baccarat-server/app/service/seed_service.py", line 37, in get_seed
    logging.info("从DB返回seed数据为空 roomid=%d gameid", room_id, game_id)
Message: '从DB返回seed数据为空 roomid=%d gameid'
Arguments: (11, 392)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.7/logging/__init__.py", line 983, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 829, in format
    return fmt.format(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 569, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.7/logging/__init__.py", line 331, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib64/python3.7/threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.7/socketserver.py", line 647, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.7/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.7/socketserver.py", line 717, in __init__
    self.handle()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 293, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib64/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 328, in handle_one_request
    return self.run_wsgi()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ec2-user/opt/python/baccarat-server/app/views.py", line 73, in generate_seed
    m = SEED_SERVICE.get_seed(int(room_id), int(game_id))
  File "/home/ec2-user/opt/python/baccarat-server/app/service/seed_service.py", line 37, in get_seed
    logging.info("从DB返回seed数据为空 roomid=%d gameid", room_id, game_id)
Message: '从DB返回seed数据为空 roomid=%d gameid'
Arguments: (11, 392)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.7/logging/__init__.py", line 983, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 829, in format
    return fmt.format(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 569, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.7/logging/__init__.py", line 331, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib64/python3.7/threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.7/socketserver.py", line 647, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.7/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.7/socketserver.py", line 717, in __init__
    self.handle()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 293, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib64/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 328, in handle_one_request
    return self.run_wsgi()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ec2-user/opt/python/baccarat-server/app/views.py", line 73, in generate_seed
    m = SEED_SERVICE.get_seed(int(room_id), int(game_id))
  File "/home/ec2-user/opt/python/baccarat-server/app/service/seed_service.py", line 37, in get_seed
    logging.info("从DB返回seed数据为空 roomid=%d gameid", room_id, game_id)
Message: '从DB返回seed数据为空 roomid=%d gameid'
Arguments: (11, 392)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.7/logging/__init__.py", line 983, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 829, in format
    return fmt.format(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 569, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.7/logging/__init__.py", line 331, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib64/python3.7/threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.7/socketserver.py", line 647, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.7/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.7/socketserver.py", line 717, in __init__
    self.handle()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 293, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib64/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 328, in handle_one_request
    return self.run_wsgi()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ec2-user/opt/python/baccarat-server/app/views.py", line 73, in generate_seed
    m = SEED_SERVICE.get_seed(int(room_id), int(game_id))
  File "/home/ec2-user/opt/python/baccarat-server/app/service/seed_service.py", line 37, in get_seed
    logging.info("从DB返回seed数据为空 roomid=%d gameid", room_id, game_id)
Message: '从DB返回seed数据为空 roomid=%d gameid'
Arguments: (11, 392)
Exception in thread Thread-2766:
Traceback (most recent call last):
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '12-2' for key 'uix_id_name'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib64/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ec2-user/opt/python/baccarat-server/app/service/reveal_service.py", line 138, in async_process_frist
    raise ex
  File "/home/ec2-user/opt/python/baccarat-server/app/service/reveal_service.py", line 134, in async_process_frist
    ROOM_ORM.insert_seed(seed_model)
  File "/home/ec2-user/opt/python/baccarat-server/app/entity/room_seed_orm.py", line 64, in insert_seed
    session.add(entity)
  File "/usr/lib64/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/home/ec2-user/opt/python/baccarat-server/app/entity/room_seed_orm.py", line 24, in session_scope
    session.commit()
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/orm/session.py", line 954, in commit
    self.transaction.commit()
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/orm/session.py", line 467, in commit
    self._prepare_impl()
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/orm/session.py", line 447, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/orm/session.py", line 2313, in flush
    self._flush(objects)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/orm/session.py", line 2440, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/orm/session.py", line 2404, in _flush
    flush_context.execute()
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 395, in execute
    rec.execute(self)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 560, in execute
    uow
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 872, in _emit_insert_statements
    execute(statement, params)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/util/compat.py", line 248, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.IntegrityError: (pymysql.err.IntegrityError) (1062, "Duplicate entry '12-2' for key 'uix_id_name'") [SQL: 'INSERT INTO room_seed (room_id, game_id, house_seed_hash, house_seed, expire_timestamp, signature, status, fail_count, created_at, environment) VALUES (%(room_id)s, %(game_id)s, %(house_seed_hash)s, %(house_seed)s, %(expire_timestamp)s, %(signature)s, %(status)s, %(fail_count)s, %(created_at)s, %(environment)s)'] [parameters: {'room_id': 12, 'game_id': 2, 'house_seed_hash': '1bea5511b43ceb70d5e745eca947793c839f32261ffb0b758785c1819b9068b1', 'house_seed': 'faaaa940587bdcb8d0fb582a7e54a9d8804b18b23dd089622188717df1374faa', 'expire_timestamp': 1544178413, 'signature': 'SIG_K1_KeTJSnirrWcVx8oAx4r9A5ZVdSo21kS9NoWCSJLdAc7aPqFZzQepdskgycnvdaSeqnz2dtz2U2bf9ZoXEEcn1RovBGjtw6', 'status': 1, 'fail_count': 0, 'created_at': 1544149559.0818727, 'environment': 'PRO'}] (Background on this error at: http://sqlalche.me/e/gkpj)

Exception in thread Thread-2763:
Traceback (most recent call last):
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '12-2' for key 'uix_id_name'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib64/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ec2-user/opt/python/baccarat-server/app/service/reveal_service.py", line 138, in async_process_frist
    raise ex
  File "/home/ec2-user/opt/python/baccarat-server/app/service/reveal_service.py", line 134, in async_process_frist
    ROOM_ORM.insert_seed(seed_model)
  File "/home/ec2-user/opt/python/baccarat-server/app/entity/room_seed_orm.py", line 64, in insert_seed
    session.add(entity)
  File "/usr/lib64/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/home/ec2-user/opt/python/baccarat-server/app/entity/room_seed_orm.py", line 24, in session_scope
    session.commit()
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/orm/session.py", line 954, in commit
    self.transaction.commit()
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/orm/session.py", line 467, in commit
    self._prepare_impl()
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/orm/session.py", line 447, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/orm/session.py", line 2313, in flush
    self._flush(objects)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/orm/session.py", line 2440, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/orm/session.py", line 2404, in _flush
    flush_context.execute()
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 395, in execute
    rec.execute(self)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 560, in execute
    uow
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 872, in _emit_insert_statements
    execute(statement, params)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/util/compat.py", line 248, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.IntegrityError: (pymysql.err.IntegrityError) (1062, "Duplicate entry '12-2' for key 'uix_id_name'") [SQL: 'INSERT INTO room_seed (room_id, game_id, house_seed_hash, house_seed, expire_timestamp, signature, status, fail_count, created_at, environment) VALUES (%(room_id)s, %(game_id)s, %(house_seed_hash)s, %(house_seed)s, %(expire_timestamp)s, %(signature)s, %(status)s, %(fail_count)s, %(created_at)s, %(environment)s)'] [parameters: {'room_id': 12, 'game_id': 2, 'house_seed_hash': '9e172f4d82e49367f0f890f18a797f03f0978c8a45ac1f64a649f49466b97266', 'house_seed': '284d42a33dbcbb31b4a1e2a836cf3e34fb19c32b24a10d1829790aaad86f42ad', 'expire_timestamp': 1544178413, 'signature': 'SIG_K1_K2zk95wm4SzybH2eJugDtuJLmEJfyruWYMXGKh352rWVWbzrnR9MtM5BRY5zubW7MhCaGhqyEVEt3iE1UGxxy9TZCRL47P', 'status': 1, 'fail_count': 0, 'created_at': 1544149559.7815025, 'environment': 'PRO'}] (Background on this error at: http://sqlalche.me/e/gkpj)

Exception in thread Thread-2764:
Traceback (most recent call last):
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '12-2' for key 'uix_id_name'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib64/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ec2-user/opt/python/baccarat-server/app/service/reveal_service.py", line 138, in async_process_frist
    raise ex
  File "/home/ec2-user/opt/python/baccarat-server/app/service/reveal_service.py", line 134, in async_process_frist
    ROOM_ORM.insert_seed(seed_model)
  File "/home/ec2-user/opt/python/baccarat-server/app/entity/room_seed_orm.py", line 64, in insert_seed
    session.add(entity)
  File "/usr/lib64/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/home/ec2-user/opt/python/baccarat-server/app/entity/room_seed_orm.py", line 24, in session_scope
    session.commit()
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/orm/session.py", line 954, in commit
    self.transaction.commit()
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/orm/session.py", line 467, in commit
    self._prepare_impl()
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/orm/session.py", line 447, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/orm/session.py", line 2313, in flush
    self._flush(objects)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/orm/session.py", line 2440, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/orm/session.py", line 2404, in _flush
    flush_context.execute()
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 395, in execute
    rec.execute(self)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 560, in execute
    uow
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 872, in _emit_insert_statements
    execute(statement, params)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/util/compat.py", line 248, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.IntegrityError: (pymysql.err.IntegrityError) (1062, "Duplicate entry '12-2' for key 'uix_id_name'") [SQL: 'INSERT INTO room_seed (room_id, game_id, house_seed_hash, house_seed, expire_timestamp, signature, status, fail_count, created_at, environment) VALUES (%(room_id)s, %(game_id)s, %(house_seed_hash)s, %(house_seed)s, %(expire_timestamp)s, %(signature)s, %(status)s, %(fail_count)s, %(created_at)s, %(environment)s)'] [parameters: {'room_id': 12, 'game_id': 2, 'house_seed_hash': '4eb806822a3abadf0005386a634271d2f2daca759aff6a7342806526a0b6498b', 'house_seed': 'f90b6c8719c67df630bf40dca22786319372cf58a7a946811e9a33598737f905', 'expire_timestamp': 1544178413, 'signature': 'SIG_K1_JyjrPdSp7VSUCytpKTG8WEGcRVkv4ZYGx3DzzsdYqBrtkqNH7vHchW1wNesxyZXUnBYE8d6mQUehVVj9tiYbrmFq9gt8yV', 'status': 1, 'fail_count': 0, 'created_at': 1544149559.3710277, 'environment': 'PRO'}] (Background on this error at: http://sqlalche.me/e/gkpj)

Exception in thread Thread-2765:
Traceback (most recent call last):
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '12-2' for key 'uix_id_name'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib64/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ec2-user/opt/python/baccarat-server/app/service/reveal_service.py", line 138, in async_process_frist
    raise ex
  File "/home/ec2-user/opt/python/baccarat-server/app/service/reveal_service.py", line 134, in async_process_frist
    ROOM_ORM.insert_seed(seed_model)
  File "/home/ec2-user/opt/python/baccarat-server/app/entity/room_seed_orm.py", line 64, in insert_seed
    session.add(entity)
  File "/usr/lib64/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/home/ec2-user/opt/python/baccarat-server/app/entity/room_seed_orm.py", line 24, in session_scope
    session.commit()
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/orm/session.py", line 954, in commit
    self.transaction.commit()
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/orm/session.py", line 467, in commit
    self._prepare_impl()
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/orm/session.py", line 447, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/orm/session.py", line 2313, in flush
    self._flush(objects)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/orm/session.py", line 2440, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/orm/session.py", line 2404, in _flush
    flush_context.execute()
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 395, in execute
    rec.execute(self)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 560, in execute
    uow
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 872, in _emit_insert_statements
    execute(statement, params)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/util/compat.py", line 248, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.IntegrityError: (pymysql.err.IntegrityError) (1062, "Duplicate entry '12-2' for key 'uix_id_name'") [SQL: 'INSERT INTO room_seed (room_id, game_id, house_seed_hash, house_seed, expire_timestamp, signature, status, fail_count, created_at, environment) VALUES (%(room_id)s, %(game_id)s, %(house_seed_hash)s, %(house_seed)s, %(expire_timestamp)s, %(signature)s, %(status)s, %(fail_count)s, %(created_at)s, %(environment)s)'] [parameters: {'room_id': 12, 'game_id': 2, 'house_seed_hash': '318b3d047a6edcc6ffd32d05c031dfbd42b9b0c8810d5c4f49211d17fbdd283a', 'house_seed': 'b3eb34883f2b6ee867334b4903041247184e6a7bf379d32e088707fb384e2d24', 'expire_timestamp': 1544178414, 'signature': 'SIG_K1_KfPp2XSgC4JDTFydYtKCnV92t82omRi3ae9YYVHwYTpkXFxjXcxdLKYBccjwFRHSNdE1GygPbybXynuWEAhsetSxR1vbeZ', 'status': 1, 'fail_count': 0, 'created_at': 1544149560.1996148, 'environment': 'PRO'}] (Background on this error at: http://sqlalche.me/e/gkpj)

Exception in thread Thread-2762:
Traceback (most recent call last):
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '12-2' for key 'uix_id_name'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib64/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ec2-user/opt/python/baccarat-server/app/service/reveal_service.py", line 138, in async_process_frist
    raise ex
  File "/home/ec2-user/opt/python/baccarat-server/app/service/reveal_service.py", line 134, in async_process_frist
    ROOM_ORM.insert_seed(seed_model)
  File "/home/ec2-user/opt/python/baccarat-server/app/entity/room_seed_orm.py", line 64, in insert_seed
    session.add(entity)
  File "/usr/lib64/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/home/ec2-user/opt/python/baccarat-server/app/entity/room_seed_orm.py", line 24, in session_scope
    session.commit()
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/orm/session.py", line 954, in commit
    self.transaction.commit()
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/orm/session.py", line 467, in commit
    self._prepare_impl()
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/orm/session.py", line 447, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/orm/session.py", line 2313, in flush
    self._flush(objects)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/orm/session.py", line 2440, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/orm/session.py", line 2404, in _flush
    flush_context.execute()
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 395, in execute
    rec.execute(self)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 560, in execute
    uow
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 872, in _emit_insert_statements
    execute(statement, params)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/util/compat.py", line 248, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.IntegrityError: (pymysql.err.IntegrityError) (1062, "Duplicate entry '12-2' for key 'uix_id_name'") [SQL: 'INSERT INTO room_seed (room_id, game_id, house_seed_hash, house_seed, expire_timestamp, signature, status, fail_count, created_at, environment) VALUES (%(room_id)s, %(game_id)s, %(house_seed_hash)s, %(house_seed)s, %(expire_timestamp)s, %(signature)s, %(status)s, %(fail_count)s, %(created_at)s, %(environment)s)'] [parameters: {'room_id': 12, 'game_id': 2, 'house_seed_hash': '4df5f5b3b00a00f7bb7bae31a26535f7e16caec220c9bb18a27936fe3c087dca', 'house_seed': 'dfaee71acf8a983f6ea38ba0c66e03080164f66d826daf430331283657c3e524', 'expire_timestamp': 1544178414, 'signature': 'SIG_K1_KiVaAPKeqMMQt8m2BxCe86JQTHndjWpKYnWaNfeP85gCkXtfHZ3zoaSs2quPmuNYttti8JLizv9bXXsT96GtWKNxabMKh6', 'status': 1, 'fail_count': 0, 'created_at': 1544149560.552793, 'environment': 'PRO'}] (Background on this error at: http://sqlalche.me/e/gkpj)
