2018-12-12 21:16:20,034 seed_service.py[line:64] ERROR generate_seed_model err [Errno 28] No space left on device
2018-12-12 21:16:20,035 reveal_service.py[line:144] ERROR [async_call_sub] 异常，重试1次 id=78767 roomid=77 game_id=482 =[Errno 28] No space left on device
2018-12-12 21:16:21,386 reveal_service.py[line:144] ERROR [async_call_sub] 异常，重试2次 id=78767 roomid=77 game_id=482 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-12 21:16:23,738 reveal_service.py[line:144] ERROR [async_call_sub] 异常，重试3次 id=78767 roomid=77 game_id=482 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-12 21:16:27,087 reveal_service.py[line:144] ERROR [async_call_sub] 异常，重试4次 id=78767 roomid=77 game_id=482 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-12 21:16:31,433 reveal_service.py[line:144] ERROR [async_call_sub] 异常，重试5次 id=78767 roomid=77 game_id=482 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-12 21:16:36,779 reveal_service.py[line:144] ERROR [async_call_sub] 异常，重试6次 id=78767 roomid=77 game_id=482 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-12 21:16:43,132 reveal_service.py[line:144] ERROR [async_call_sub] 异常，重试7次 id=78767 roomid=77 game_id=482 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-12 21:16:50,483 reveal_service.py[line:144] ERROR [async_call_sub] 异常，重试8次 id=78767 roomid=77 game_id=482 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-12 21:16:58,837 reveal_service.py[line:144] ERROR [async_call_sub] 异常，重试9次 id=78767 roomid=77 game_id=482 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-12 21:17:08,250 reveal_service.py[line:144] ERROR [async_call_sub] 异常，重试10次 id=78767 roomid=77 game_id=482 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-13 02:26:16,622 seed_service.py[line:64] ERROR generate_seed_model err [Errno 28] No space left on device
2018-12-13 02:26:16,623 reveal_service.py[line:144] ERROR [async_call_sub] 异常，重试1次 id=80896 roomid=80 game_id=832 =[Errno 28] No space left on device
2018-12-13 02:26:18,209 reveal_service.py[line:144] ERROR [async_call_sub] 异常，重试2次 id=80896 roomid=80 game_id=832 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-13 02:26:20,868 reveal_service.py[line:144] ERROR [async_call_sub] 异常，重试3次 id=80896 roomid=80 game_id=832 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-13 13:04:30,740 seed_service.py[line:44] ERROR get_seed 异常 =no seed data
2018-12-13 13:04:30,741 views.py[line:123] ERROR api get_seed 异常=no seed data
2018-12-13 13:04:47,948 seed_service.py[line:44] ERROR get_seed 异常 =no seed data
2018-12-13 13:04:47,948 views.py[line:123] ERROR api get_seed 异常=no seed data
2018-12-13 13:04:58,383 seed_service.py[line:44] ERROR get_seed 异常 =no seed data
2018-12-13 13:04:58,384 views.py[line:123] ERROR api get_seed 异常=no seed data
2018-12-13 13:10:04,198 seed_service.py[line:44] ERROR get_seed 异常 =no seed data
2018-12-13 13:10:04,198 views.py[line:123] ERROR api get_seed 异常=no seed data
2018-12-13 13:10:26,265 seed_service.py[line:44] ERROR get_seed 异常 =no seed data
2018-12-13 13:10:26,265 views.py[line:123] ERROR api get_seed 异常=no seed data
2018-12-13 13:11:33,239 seed_service.py[line:44] ERROR get_seed 异常 =no seed data
2018-12-13 13:11:33,239 views.py[line:123] ERROR api get_seed 异常=no seed data
2018-12-13 13:30:12,716 seed_service.py[line:44] ERROR get_seed 异常 =no seed data
2018-12-13 13:30:12,716 views.py[line:123] ERROR api get_seed 异常=no seed data
2018-12-13 13:30:25,100 seed_service.py[line:44] ERROR get_seed 异常 =no seed data
2018-12-13 13:30:25,100 views.py[line:123] ERROR api get_seed 异常=no seed data
2018-12-13 13:30:48,424 seed_service.py[line:44] ERROR get_seed 异常 =no seed data
2018-12-13 13:30:48,424 views.py[line:123] ERROR api get_seed 异常=no seed data
2018-12-13 13:30:57,276 seed_service.py[line:44] ERROR get_seed 异常 =no seed data
2018-12-13 13:30:57,276 views.py[line:123] ERROR api get_seed 异常=no seed data
2018-12-13 13:31:06,154 seed_service.py[line:44] ERROR get_seed 异常 =no seed data
2018-12-13 13:31:06,159 views.py[line:123] ERROR api get_seed 异常=no seed data
2018-12-13 13:31:33,463 seed_service.py[line:44] ERROR get_seed 异常 =no seed data
2018-12-13 13:31:33,464 views.py[line:123] ERROR api get_seed 异常=no seed data
2018-12-13 13:32:35,222 seed_service.py[line:44] ERROR get_seed 异常 =no seed data
2018-12-13 13:32:35,223 views.py[line:123] ERROR api get_seed 异常=no seed data
2018-12-13 13:33:29,939 seed_service.py[line:44] ERROR get_seed 异常 =no seed data
2018-12-13 13:33:29,939 views.py[line:123] ERROR api get_seed 异常=no seed data
2018-12-13 13:34:10,876 seed_service.py[line:44] ERROR get_seed 异常 =no seed data
2018-12-13 13:34:10,876 views.py[line:123] ERROR api get_seed 异常=no seed data
2018-12-13 13:37:48,172 seed_service.py[line:125] ERROR no seed data
2018-12-13 13:37:48,172 seed_service.py[line:44] ERROR get_seed 异常 =no seed data
2018-12-13 13:37:48,172 views.py[line:123] ERROR api get_seed 异常=no seed data
2018-12-13 13:37:54,775 seed_service.py[line:44] ERROR get_seed 异常 =no seed data
2018-12-13 13:37:54,775 views.py[line:123] ERROR api get_seed 异常=no seed data
2018-12-13 14:34:38,024 reveal_service.py[line:144] ERROR [async_call_sub] 异常，重试1次 id=85891 roomid=77 game_id=1669 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-13 14:34:39,824 reveal_service.py[line:144] ERROR [async_call_sub] 异常，重试2次 id=85891 roomid=77 game_id=1669 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-13 14:34:42,504 reveal_service.py[line:144] ERROR [async_call_sub] 异常，重试3次 id=85891 roomid=77 game_id=1669 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-13 14:34:46,181 reveal_service.py[line:144] ERROR [async_call_sub] 异常，重试4次 id=85891 roomid=77 game_id=1669 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-13 14:34:50,808 reveal_service.py[line:144] ERROR [async_call_sub] 异常，重试5次 id=85891 roomid=77 game_id=1669 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-13 14:34:56,470 reveal_service.py[line:144] ERROR [async_call_sub] 异常，重试6次 id=85891 roomid=77 game_id=1669 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-13 14:35:03,094 reveal_service.py[line:144] ERROR [async_call_sub] 异常，重试7次 id=85891 roomid=77 game_id=1669 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-13 14:35:10,640 reveal_service.py[line:144] ERROR [async_call_sub] 异常，重试8次 id=85891 roomid=77 game_id=1669 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-13 14:35:19,094 reveal_service.py[line:144] ERROR [async_call_sub] 异常，重试9次 id=85891 roomid=77 game_id=1669 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-13 15:52:28,897 reveal_service.py[line:144] ERROR [async_call_sub] 异常，重试1次 id=86426 roomid=80 game_id=1753 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-13 15:52:30,486 reveal_service.py[line:144] ERROR [async_call_sub] 异常，重试2次 id=86426 roomid=80 game_id=1753 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-13 15:52:33,126 reveal_service.py[line:144] ERROR [async_call_sub] 异常，重试3次 id=86426 roomid=80 game_id=1753 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-13 15:52:36,590 reveal_service.py[line:144] ERROR [async_call_sub] 异常，重试4次 id=86426 roomid=80 game_id=1753 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-13 15:52:41,116 reveal_service.py[line:144] ERROR [async_call_sub] 异常，重试5次 id=86426 roomid=80 game_id=1753 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-13 15:52:46,752 reveal_service.py[line:144] ERROR [async_call_sub] 异常，重试6次 id=86426 roomid=80 game_id=1753 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-13 15:52:53,351 reveal_service.py[line:144] ERROR [async_call_sub] 异常，重试7次 id=86426 roomid=80 game_id=1753 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-13 15:53:01,101 reveal_service.py[line:144] ERROR [async_call_sub] 异常，重试8次 id=86426 roomid=80 game_id=1753 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-13 15:53:09,501 reveal_service.py[line:144] ERROR [async_call_sub] 异常，重试9次 id=86426 roomid=80 game_id=1753 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-13 17:07:47,945 reveal_service.py[line:144] ERROR [async_call_sub] 异常，重试1次 id=86941 roomid=80 game_id=1839 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-13 17:07:49,562 reveal_service.py[line:144] ERROR [async_call_sub] 异常，重试2次 id=86941 roomid=80 game_id=1839 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-13 17:07:52,208 reveal_service.py[line:144] ERROR [async_call_sub] 异常，重试3次 id=86941 roomid=80 game_id=1839 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-13 17:07:55,923 reveal_service.py[line:144] ERROR [async_call_sub] 异常，重试4次 id=86941 roomid=80 game_id=1839 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-13 17:08:00,505 reveal_service.py[line:144] ERROR [async_call_sub] 异常，重试5次 id=86941 roomid=80 game_id=1839 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-13 17:08:06,020 reveal_service.py[line:144] ERROR [async_call_sub] 异常，重试6次 id=86941 roomid=80 game_id=1839 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-13 17:08:12,621 reveal_service.py[line:144] ERROR [async_call_sub] 异常，重试7次 id=86941 roomid=80 game_id=1839 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-13 17:08:20,134 reveal_service.py[line:144] ERROR [async_call_sub] 异常，重试8次 id=86941 roomid=80 game_id=1839 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-13 17:08:28,740 reveal_service.py[line:144] ERROR [async_call_sub] 异常，重试9次 id=86941 roomid=80 game_id=1839 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-13 20:08:53,415 reveal_service.py[line:144] ERROR [async_call_sub] 异常，重试1次 id=88183 roomid=80 game_id=2046 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-13 20:08:55,071 reveal_service.py[line:144] ERROR [async_call_sub] 异常，重试2次 id=88183 roomid=80 game_id=2046 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-13 20:08:57,523 reveal_service.py[line:144] ERROR [async_call_sub] 异常，重试3次 id=88183 roomid=80 game_id=2046 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-13 20:09:01,132 reveal_service.py[line:144] ERROR [async_call_sub] 异常，重试4次 id=88183 roomid=80 game_id=2046 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-13 20:09:05,729 reveal_service.py[line:144] ERROR [async_call_sub] 异常，重试5次 id=88183 roomid=80 game_id=2046 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-13 20:09:11,325 reveal_service.py[line:144] ERROR [async_call_sub] 异常，重试6次 id=88183 roomid=80 game_id=2046 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-13 20:09:17,859 reveal_service.py[line:144] ERROR [async_call_sub] 异常，重试7次 id=88183 roomid=80 game_id=2046 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-13 20:09:25,381 reveal_service.py[line:144] ERROR [async_call_sub] 异常，重试8次 id=88183 roomid=80 game_id=2046 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-13 20:09:33,885 reveal_service.py[line:144] ERROR [async_call_sub] 异常，重试9次 id=88183 roomid=80 game_id=2046 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-13 20:50:02,335 reveal_service.py[line:144] ERROR [async_call_sub] 异常，重试1次 id=88464 roomid=79 game_id=2093 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-13 20:50:03,952 reveal_service.py[line:144] ERROR [async_call_sub] 异常，重试2次 id=88464 roomid=79 game_id=2093 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-13 20:50:06,459 reveal_service.py[line:144] ERROR [async_call_sub] 异常，重试3次 id=88464 roomid=79 game_id=2093 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-13 20:50:10,076 reveal_service.py[line:144] ERROR [async_call_sub] 异常，重试4次 id=88464 roomid=79 game_id=2093 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-13 20:50:14,676 reveal_service.py[line:144] ERROR [async_call_sub] 异常，重试5次 id=88464 roomid=79 game_id=2093 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-13 20:50:20,341 reveal_service.py[line:144] ERROR [async_call_sub] 异常，重试6次 id=88464 roomid=79 game_id=2093 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-13 20:50:26,862 reveal_service.py[line:144] ERROR [async_call_sub] 异常，重试7次 id=88464 roomid=79 game_id=2093 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-13 20:50:34,447 reveal_service.py[line:144] ERROR [async_call_sub] 异常，重试8次 id=88464 roomid=79 game_id=2093 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-13 20:50:42,961 reveal_service.py[line:144] ERROR [async_call_sub] 异常，重试9次 id=88464 roomid=79 game_id=2093 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
