2018-12-08 12:31:18,535 reveal_service.py[line:128] ERROR [async_call_sub] 异常，重试1次 id=41129 roomid=12 game_id=2059 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-08 13:33:36,452 reveal_service.py[line:128] ERROR [async_call_sub] 异常，重试1次 id=41838 roomid=12 game_id=2130 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-08 14:15:36,836 reveal_service.py[line:128] ERROR [async_call_sub] 异常，重试1次 id=42316 roomid=1 game_id=4188 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-08 15:43:48,417 reveal_service.py[line:128] ERROR [async_call_sub] 异常，重试1次 id=43320 roomid=6 game_id=4239 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-08 17:47:42,473 reveal_service.py[line:128] ERROR [async_call_sub] 异常，重试1次 id=44559 roomid=8 game_id=3865 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-08 19:18:00,816 reveal_service.py[line:128] ERROR [async_call_sub] 异常，重试1次 id=45457 roomid=1 game_id=4531 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-08 20:09:06,919 reveal_service.py[line:128] ERROR [async_call_sub] 异常，重试1次 id=46004 roomid=6 game_id=4540 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-08 20:16:38,787 seed_service.py[line:125] ERROR no seed data
2018-12-08 20:16:38,787 seed_service.py[line:44] ERROR get_seed 异常 =no seed data
2018-12-08 20:16:38,787 views.py[line:78] ERROR api get_seed 异常=no seed data
2018-12-08 20:21:57,645 seed_service.py[line:125] ERROR no seed data
2018-12-08 20:21:57,645 seed_service.py[line:44] ERROR get_seed 异常 =no seed data
2018-12-08 20:21:57,645 views.py[line:78] ERROR api get_seed 异常=no seed data
2018-12-08 20:54:10,419 seed_service.py[line:125] ERROR no seed data
2018-12-08 20:54:10,419 seed_service.py[line:44] ERROR get_seed 异常 =no seed data
2018-12-08 20:54:10,419 views.py[line:78] ERROR api get_seed 异常=no seed data
2018-12-08 21:11:17,303 reveal_service.py[line:128] ERROR [async_call_sub] 异常，重试1次 id=46640 roomid=24 game_id=1952 =b'error 2018-12-08T21:11:17.302 thread-0  main.cpp:3151                 main                 ] Failed with error: Parse Error (4)\nUnexpected char \'60\' in ""\n\n\n'
2018-12-08 21:11:24,604 reveal_service.py[line:128] ERROR [async_call_sub] 异常，重试1次 id=46642 roomid=8 game_id=4097 =b'error 2018-12-08T21:11:24.602 thread-0  main.cpp:3151                 main                 ] Failed with error: Parse Error (4)\nUnexpected char \'60\' in ""\n\n\n'
2018-12-08 21:11:54,985 reveal_service.py[line:128] ERROR [async_call_sub] 异常，重试1次 id=46644 roomid=12 game_id=2578 =b'error 2018-12-08T21:11:54.983 thread-0  main.cpp:3151                 main                 ] Failed with error: Parse Error (4)\nUnexpected char \'60\' in ""\n\n\n'
2018-12-08 21:11:59,785 reveal_service.py[line:50] ERROR 〓REVEAL〓 自动开奖-获取房间信息遍历执行异常 =Expecting value: line 2 column 1 (char 1)
2018-12-08 21:12:11,725 seed_service.py[line:125] ERROR no seed data
2018-12-08 21:12:11,725 seed_service.py[line:44] ERROR get_seed 异常 =no seed data
2018-12-08 21:12:11,725 views.py[line:78] ERROR api get_seed 异常=no seed data
2018-12-08 21:16:22,826 reveal_service.py[line:50] ERROR 〓REVEAL〓 自动开奖-获取房间信息遍历执行异常 =Expecting value: line 2 column 1 (char 1)
2018-12-08 21:21:09,532 reveal_service.py[line:50] ERROR 〓REVEAL〓 自动开奖-获取房间信息遍历执行异常 =Expecting value: line 2 column 1 (char 1)
2018-12-08 22:20:11,047 seed_service.py[line:125] ERROR no seed data
2018-12-08 22:20:11,047 seed_service.py[line:44] ERROR get_seed 异常 =no seed data
2018-12-08 22:20:11,047 views.py[line:78] ERROR api get_seed 异常=no seed data
2018-12-08 22:26:50,702 seed_service.py[line:125] ERROR no seed data
2018-12-08 22:26:50,708 seed_service.py[line:44] ERROR get_seed 异常 =no seed data
2018-12-08 22:26:50,713 views.py[line:78] ERROR api get_seed 异常=no seed data
2018-12-08 23:08:20,137 seed_service.py[line:125] ERROR no seed data
2018-12-08 23:08:20,137 seed_service.py[line:44] ERROR get_seed 异常 =no seed data
2018-12-08 23:08:20,137 views.py[line:78] ERROR api get_seed 异常=no seed data
2018-12-08 23:10:46,547 seed_service.py[line:125] ERROR no seed data
2018-12-08 23:10:46,547 seed_service.py[line:44] ERROR get_seed 异常 =no seed data
2018-12-08 23:10:46,547 views.py[line:78] ERROR api get_seed 异常=no seed data
2018-12-08 23:35:47,018 seed_service.py[line:125] ERROR no seed data
2018-12-08 23:35:47,018 seed_service.py[line:44] ERROR get_seed 异常 =no seed data
2018-12-08 23:35:47,018 views.py[line:78] ERROR api get_seed 异常=no seed data
2018-12-09 00:06:16,913 seed_service.py[line:125] ERROR no seed data
2018-12-09 00:06:16,913 seed_service.py[line:44] ERROR get_seed 异常 =no seed data
2018-12-09 00:06:16,913 views.py[line:78] ERROR api get_seed 异常=no seed data
2018-12-09 00:06:56,313 seed_service.py[line:125] ERROR no seed data
2018-12-09 00:06:56,325 seed_service.py[line:44] ERROR get_seed 异常 =no seed data
2018-12-09 00:06:56,331 views.py[line:78] ERROR api get_seed 异常=no seed data
2018-12-09 00:09:56,796 seed_service.py[line:125] ERROR no seed data
2018-12-09 00:09:56,797 seed_service.py[line:44] ERROR get_seed 异常 =no seed data
2018-12-09 00:09:56,797 views.py[line:78] ERROR api get_seed 异常=no seed data
2018-12-09 00:10:47,044 seed_service.py[line:125] ERROR no seed data
2018-12-09 00:10:47,044 seed_service.py[line:44] ERROR get_seed 异常 =no seed data
2018-12-09 00:10:47,044 views.py[line:78] ERROR api get_seed 异常=no seed data
2018-12-09 00:11:11,731 seed_service.py[line:125] ERROR no seed data
2018-12-09 00:11:11,731 seed_service.py[line:44] ERROR get_seed 异常 =no seed data
2018-12-09 00:11:11,732 views.py[line:78] ERROR api get_seed 异常=no seed data
2018-12-09 00:11:27,069 seed_service.py[line:125] ERROR no seed data
2018-12-09 00:11:27,069 seed_service.py[line:44] ERROR get_seed 异常 =no seed data
2018-12-09 00:11:27,069 views.py[line:78] ERROR api get_seed 异常=no seed data
2018-12-09 00:14:55,124 seed_service.py[line:125] ERROR no seed data
2018-12-09 00:14:55,124 seed_service.py[line:44] ERROR get_seed 异常 =no seed data
2018-12-09 00:14:55,124 views.py[line:78] ERROR api get_seed 异常=no seed data
2018-12-09 00:15:38,963 seed_service.py[line:125] ERROR no seed data
2018-12-09 00:15:38,963 seed_service.py[line:44] ERROR get_seed 异常 =no seed data
2018-12-09 00:15:38,963 views.py[line:78] ERROR api get_seed 异常=no seed data
2018-12-09 00:52:43,318 seed_service.py[line:125] ERROR no seed data
2018-12-09 00:52:43,318 seed_service.py[line:44] ERROR get_seed 异常 =no seed data
2018-12-09 00:52:43,318 views.py[line:78] ERROR api get_seed 异常=no seed data
2018-12-09 00:52:43,321 seed_service.py[line:125] ERROR no seed data
2018-12-09 00:52:43,321 seed_service.py[line:44] ERROR get_seed 异常 =no seed data
2018-12-09 00:52:43,322 views.py[line:78] ERROR api get_seed 异常=no seed data
2018-12-09 00:52:43,567 seed_service.py[line:125] ERROR no seed data
2018-12-09 00:52:43,567 seed_service.py[line:44] ERROR get_seed 异常 =no seed data
2018-12-09 00:52:43,567 views.py[line:78] ERROR api get_seed 异常=no seed data
