2018-12-09 05:52:44,283 reveal_service.py[line:91] ERROR process异常 =Instance <RoomSeedTb at 0x7f3772d185c0> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: http://sqlalche.me/e/bhk3)
2018-12-09 05:52:44,283 reveal_service.py[line:52] ERROR 〓REVEAL〓 自动开奖 =Instance <RoomSeedTb at 0x7f3772d185c0> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: http://sqlalche.me/e/bhk3)
